/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package th04;

import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class GIAODIENCHINH extends javax.swing.JFrame {

    /**
     * Creates new form GIAODIENCHINH
     */
    public GIAODIENCHINH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FILE = new javax.swing.JLabel();
        btnMANH1 = new javax.swing.JButton();
        btnMANH2 = new javax.swing.JButton();
        btnSANPHAM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FILE.setText("FILE");

        btnMANH1.setText("MANH 1");
        btnMANH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMANH1ActionPerformed(evt);
            }
        });

        btnMANH2.setText("MANH 2");
        btnMANH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMANH2ActionPerformed(evt);
            }
        });

        btnSANPHAM.setText("SANPHAM");
        btnSANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSANPHAMActionPerformed(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane2.setViewportView(txtError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FILE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMANH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMANH2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSANPHAM)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FILE)
                    .addComponent(btnMANH1)
                    .addComponent(btnMANH2)
                    .addComponent(btnSANPHAM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMANH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMANH1ActionPerformed
        File f = new File("D:/sanpham_1.txt");
        DataModel db = new DataModel();
        String tenCot[]={"Ma San Pham","Ten San Pham","Gia Ban","Ma Kho"};
        tblmodel = new DefaultTableModel(tenCot,0);
        db.getDataSanPham(f, tblmodel, tblResult, txtError, tenCot);
    }//GEN-LAST:event_btnMANH1ActionPerformed

    private void btnMANH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMANH2ActionPerformed
        File f = new File("D:/sanpham_2.txt");
        DataModel db = new DataModel();
        String tenCot[]={"Ma San Pham","Ten San Pham","Gia Ban","Ma Kho"};
        db.getDataSanPham(f, tblmodel, tblResult, txtError, tenCot);  
    }//GEN-LAST:event_btnMANH2ActionPerformed

    private void btnSANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSANPHAMActionPerformed
        DataModel db = new DataModel();
        String tenCot[]={"Ma San Pham","Ten San Pham","Gia Ban","Ma Kho"};
        tblmodel = new DefaultTableModel(tenCot,0);
        File f = new File("D:/sanpham_1.txt");
        db.getDataSanPham(f, tblmodel, tblResult, txtError, tenCot);
        f = new File("D:/sanpham_2.txt");
        db.getDataSanPham(f, tblmodel, tblResult, txtError, tenCot);        
    }//GEN-LAST:event_btnSANPHAMActionPerformed

    
    private DefaultTableModel tblmodel = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FILE;
    private javax.swing.JButton btnMANH1;
    private javax.swing.JButton btnMANH2;
    private javax.swing.JButton btnSANPHAM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables
}
