package csdlpt;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;

// === THÊM CÁC IMPORT NÀY ===
import java.awt.Font; 
import javax.swing.border.EmptyBorder;
// =============================

/**
 * Cửa sổ chính (JFrame), chứa 5 Tab (JPanel)
 *
 * @author duc18
 */
public class MainForm extends javax.swing.JFrame {

    // === 1. BIẾN LOGIC ===
    private DataModel dataModel;
    private File ipFile;

    // === 2. BIẾN GIAO DIỆN ===
    private JTabbedPane jTabbedPane1;
    private JTextArea txtLogOutput;

    // 5 Panel tương ứng 5 Tab
    private NhanVien panelNhanVien;
    private ChiNhanh panelChiNhanh;
    private KhachHang panelKhachHang;
    private HopDong panelHopDong;
    private HoaDon panelHoaDon;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        // Khởi tạo logic trước
        dataModel = new DataModel();

        // !!! QUAN TRỌNG: Sửa đường dẫn này cho đúng !!!
        ipFile = new File("D:\\CSDLPTDOANTH\\CSDLPTDOANTH\\IP.txt");

        // Khởi tạo giao diện (Hàm do NetBeans tạo)
        initComponents();

        // === THÊM CẤU HÌNH CHO LOG OUTPUT (Cho đẹp hơn) ===
        txtLogOutput.setFont(new Font("Segoe UI", Font.PLAIN, 14)); // Tăng cỡ chữ
        txtLogOutput.setEditable(false); // Không cho phép gõ
        txtLogOutput.setLineWrap(true); // Tự động xuống dòng
        txtLogOutput.setWrapStyleWord(true); // Xuống dòng theo từ
        txtLogOutput.setBorder(new EmptyBorder(5, 5, 5, 5)); // Thêm đệm (padding)
        // =================================================

        // "Bơm" logic vào các Panel
        panelChiNhanh.init(dataModel, ipFile, txtLogOutput);
        panelNhanVien.init(dataModel, ipFile, txtLogOutput);
        panelKhachHang.init(dataModel, ipFile, txtLogOutput);
        panelHopDong.init(dataModel, ipFile, txtLogOutput);
        panelHoaDon.init(dataModel, ipFile, txtLogOutput);

        // Cấu hình cửa sổ
        setTitle("Quản Lý Điện Lực Phân Tán");
        setSize(800, 600); // Set kích thước
        setLocationRelativeTo(null); // Giữa màn hình

        if (!ipFile.exists()) {
            txtLogOutput.setText("LỖI: Không tìm thấy file ip.txt tại: " + ipFile.getAbsolutePath());
        } else {
            txtLogOutput.setText("Sẵn sàng. Vui lòng chọn Tab và tải dữ liệu.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. (Đây là code NetBeans tự tạo khi bạn kéo
     * thả)
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane_Log = new javax.swing.JScrollPane();
        txtLogOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // === ĐÂY LÀ PHẦN KẾT NỐI ===
        // Tạo 5 Panel
        panelChiNhanh = new ChiNhanh();
        panelNhanVien = new NhanVien();
        panelKhachHang = new KhachHang();
        panelHopDong = new HopDong();
        panelHoaDon = new HoaDon();

        // Thêm 5 Panel vào 5 Tab
        jTabbedPane1.addTab("Chi Nhánh", panelChiNhanh);
        jTabbedPane1.addTab("Nhân Viên", panelNhanVien);
        jTabbedPane1.addTab("Khách Hàng", panelKhachHang);
        jTabbedPane1.addTab("Hợp Đồng", panelHopDong);
        jTabbedPane1.addTab("Hóa Đơn", panelHoaDon);

        // Đặt JTabbedPane vào giữa
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        // === THAY ĐỔI CHIỀU CAO LOG ===
        txtLogOutput.setColumns(20);
        txtLogOutput.setRows(8); // <-- TĂNG TỪ 5 LÊN 8
        // ===============================
        
        jScrollPane_Log.setViewportView(txtLogOutput);

        getContentPane().add(jScrollPane_Log, java.awt.BorderLayout.SOUTH);

        pack(); // Tự động điều chỉnh kích thước
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane_Log;
    // End of variables declaration//GEN-END:variables
}