package csdlpt;

// Import các thư viện cần thiết
import java.awt.BorderLayout;
import java.awt.FlowLayout; // Thêm import
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTextArea;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

// Thêm các import cho giao diện mới
import javax.swing.JSplitPane;
import javax.swing.JPanel;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.BorderFactory;

/**
 * Đây là giao diện (JPanel) CHỈ DÀNH CHO TAB NHÂN VIÊN
 * (Đã cập nhật giao diện Master-Detail Trái/Phải)
 * @author duc18
 */
public class NhanVien extends javax.swing.JPanel {

    // === 1. BIẾN LOGIC (Giữ nguyên) ===
    private DataModel dataModel;
    private File ipFile;
    private JTextArea txtLogOutput;

    /**
     * Creates new form NhanVienPanel
     */
    public NhanVien() {
        initComponents(); 
        addTableListeners(); 
    }

    /**
     * HÀM QUAN TRỌNG: MainForm sẽ gọi hàm này để "bơm" logic vào
     */
    public void init(DataModel model, File file, JTextArea log) {
        this.dataModel = model;
        this.ipFile = file;
        this.txtLogOutput = log;
    }
    
    /**
     * Hàm tự động điền dữ liệu khi click vào bảng
     */
    private void addTableListeners() {
        tblNhanVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && tblNhanVien.getSelectedRow() != -1) {
                    int row = tblNhanVien.getSelectedRow();
                    txtMaNV.setText(tblNhanVien.getValueAt(row, 0).toString());
                    txtHoTen.setText(tblNhanVien.getValueAt(row, 1).toString());
                    txtMaCN_NV.setText(tblNhanVien.getValueAt(row, 2).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * * (KHỐI CODE NÀY ĐÃ ĐƯỢC THIẾT KẾ LẠI HOÀN TOÀN)
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // --- KHAI BÁO BIẾN GIAO DIỆN ---
        // Biến mới
        jSplitPane1 = new javax.swing.JSplitPane();
        panelForm = new javax.swing.JPanel(); // Panel bên trái
        panelButtons = new javax.swing.JPanel(); // Panel chứa các nút
        
        // Biến cũ
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtMaCN_NV = new javax.swing.JTextField();
        btnLoadNV = new javax.swing.JButton();
        btnAddNV = new javax.swing.JButton();
        btnUpdateNV = new javax.swing.JButton();
        btnDeleteNV = new javax.swing.JButton();

        // --- CẤU HÌNH PANEL CHÍNH (NhanVien.java) ---
        // 1. Dùng BorderLayout
        setLayout(new java.awt.BorderLayout());

        // --- CẤU HÌNH PANEL BÊN PHẢI (Bảng) ---
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Tên", "Mã CN"
            }
        ));
        jScrollPane1.setViewportView(tblNhanVien);
        
        // --- CẤU HÌNH PANEL BÊN TRÁI (Form Nhập liệu) ---
        panelForm.setBorder(BorderFactory.createTitledBorder("Thông tin Nhân Viên"));
        
        jLabel1.setText("Mã Nhân Viên:");
        jLabel2.setText("Tên Nhân Viên:");
        jLabel3.setText("Mã Chi Nhánh:");

        // Cấu hình panel chứa các nút (dùng FlowLayout để các nút nằm ngang)
        panelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 5));

        btnLoadNV.setText("Tải Lại");
        btnLoadNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadNVActionPerformed(evt);
            }
        });
        panelButtons.add(btnLoadNV);

        btnAddNV.setText("Thêm");
        btnAddNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNVActionPerformed(evt);
            }
        });
        panelButtons.add(btnAddNV);

        btnUpdateNV.setText("Sửa");
        btnUpdateNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNVActionPerformed(evt);
            }
        });
        panelButtons.add(btnUpdateNV);

        btnDeleteNV.setText("Xóa");
        btnDeleteNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNVActionPerformed(evt);
            }
        });
        panelButtons.add(btnDeleteNV);

        // --- Sắp xếp layout cho panelForm (Dùng GroupLayout) ---
        // Sắp xếp các label, textfield, và panel nút theo chiều dọc
        GroupLayout panelFormLayout = new GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setAutoCreateGaps(true);
        panelFormLayout.setAutoCreateContainerGaps(true);

        // -- Căn chỉnh chiều ngang (Horizontal) --
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNV)
                    .addComponent(txtHoTen)
                    .addComponent(txtMaCN_NV)))
            .addComponent(panelButtons, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        // -- Căn chỉnh chiều dọc (Vertical) --
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaCN_NV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18) // Thêm khoảng cách
                .addComponent(panelButtons, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        // --- CẤU HÌNH THANH CHIA (JSplitPane) ---
        jSplitPane1.setLeftComponent(panelForm);    // Đặt form bên trái
        jSplitPane1.setRightComponent(jScrollPane1); // Đặt bảng bên phải
        jSplitPane1.setDividerLocation(350);         // Đặt vị trí thanh chia ban đầu
        jSplitPane1.setOneTouchExpandable(true);     // Cho phép thu gọn/mở rộng nhanh

        // 4. Thêm JSplitPane vào panel chính (NhanVien.java)
        add(jSplitPane1, java.awt.BorderLayout.CENTER);
        
    }// </editor-fold>//GEN-END:initComponents

    // === CÁC HÀM SỰ KIỆN (Không có gì thay đổi, giữ nguyên) ===
    
    private void btnLoadNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNVActionPerformed
        String endpoint = "/NHANVIEN/Index"; 
        txtLogOutput.setText("Đang tải dữ liệu Nhân Viên từ tất cả các site...\n");
        
        // --- CHẠY TRÊN LUỒNG MỚI ---
        new Thread(() -> {
            setAllButtonsEnabled(false);
            dataModel.getDataFromAllSites(ipFile, tblNhanVien, txtLogOutput, endpoint);
            javax.swing.SwingUtilities.invokeLater(() -> {
                setAllButtonsEnabled(true);
            });
        }).start();
    }//GEN-LAST:event_btnLoadNVActionPerformed

    private void btnAddNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNVActionPerformed
        String endpoint = "/NHANVIEN/Add"; 
        Map<String, String> params = new HashMap<>();
        params.put("maNV", txtMaNV.getText());
        params.put("hoten", txtHoTen.getText());
        params.put("maCN", txtMaCN_NV.getText());

        if (params.get("maNV").isEmpty() || params.get("hoten").isEmpty() || params.get("maCN").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã NV, Họ Tên, Mã CN không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        txtLogOutput.setText("Đang gửi lệnh THÊM Nhân Viên đến MÁY CHÍNH...\n");
        
        // --- CHẠY TRÊN LUỒNG MỚI VÀ KIỂM TRA KẾT QUẢ ---
        new Thread(() -> {
            setAllButtonsEnabled(false);
            boolean isSuccess = dataModel.postToMaster(txtLogOutput, params, endpoint);
            
            if (isSuccess) {
                txtLogOutput.append("\nĐang tải lại dữ liệu (chờ Replication)...");
                try { Thread.sleep(2000); } catch (Exception e) {} 
                btnLoadNVActionPerformed(null);
            } else {
                txtLogOutput.append("\n==> THÊM THẤT BẠI. Dữ liệu sẽ không được tải lại.");
                 javax.swing.SwingUtilities.invokeLater(() -> {
                    setAllButtonsEnabled(true);
                });
            }
        }).start();
    }//GEN-LAST:event_btnAddNVActionPerformed

    private void btnUpdateNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNVActionPerformed
        String endpoint = "/NHANVIEN/Update"; 
        Map<String, String> params = new HashMap<>();
        params.put("maNV", txtMaNV.getText());
        params.put("hoten", txtHoTen.getText());
        params.put("maCN", txtMaCN_NV.getText()); 

        if (params.get("maNV").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một Nhân Viên (Mã NV) để sửa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        txtLogOutput.setText("Đang gửi lệnh SỬA Nhân Viên đến MÁY CHÍNH...\n");
        
        // --- CHẠY TRÊN LUỒNG MỚI VÀ KIỂM TRA KẾT QUẢ ---
        new Thread(() -> {
            setAllButtonsEnabled(false);
            boolean isSuccess = dataModel.postToMaster(txtLogOutput, params, endpoint);
            
            if (isSuccess) {
                txtLogOutput.append("\nĐang tải lại dữ liệu (chờ Replication)...");
                try { Thread.sleep(2000); } catch (Exception e) {}
                btnLoadNVActionPerformed(null);
            } else {
                txtLogOutput.append("\n==> SỬA THẤT BẠI. Dữ liệu sẽ không được tải lại.");
                 javax.swing.SwingUtilities.invokeLater(() -> {
                    setAllButtonsEnabled(true);
                });
            }
        }).start();
    }//GEN-LAST:event_btnUpdateNVActionPerformed

    private void btnDeleteNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNVActionPerformed
        String endpoint = "/NHANVIEN/Delete"; 
        Map<String, String> params = new HashMap<>();
        params.put("maNV", txtMaNV.getText()); 

        if (params.get("maNV").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn một Nhân Viên (Mã NV) để xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa Nhân Viên: " + params.get("maNV") + "?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        txtLogOutput.setText("Đang gửi lệnh XÓA Nhân Viên đến MÁY CHÍNH...\n");
        
        // --- CHẠY TRÊN LUỒNG MỚI VÀ KIỂM TRA KẾT QUẢ ---
        new Thread(() -> {
            setAllButtonsEnabled(false);
            boolean isSuccess = dataModel.postToMaster(txtLogOutput, params, endpoint);
            
            if (isSuccess) {
                txtLogOutput.append("\nĐang tải lại dữ liệu (chờ Replication)...");
                try { Thread.sleep(2000); } catch (Exception e) {}
                btnLoadNVActionPerformed(null);
            } else {
                 txtLogOutput.append("\n==> XÓA THẤT BẠI. Dữ liệu sẽ không được tải lại.");
                 javax.swing.SwingUtilities.invokeLater(() -> {
                    setAllButtonsEnabled(true);
                });
            }
        }).start();
    }//GEN-LAST:event_btnDeleteNVActionPerformed

    /**
     * Hàm tiện ích để bật/tắt tất cả các nút (chạy trên luồng giao diện)
     */
    private void setAllButtonsEnabled(boolean enabled) {
        if (javax.swing.SwingUtilities.isEventDispatchThread()) {
            btnLoadNV.setEnabled(enabled);
            btnAddNV.setEnabled(enabled);
            btnUpdateNV.setEnabled(enabled);
            btnDeleteNV.setEnabled(enabled);
        } else {
            javax.swing.SwingUtilities.invokeLater(() -> {
                btnLoadNV.setEnabled(enabled);
                btnAddNV.setEnabled(enabled);
                btnUpdateNV.setEnabled(enabled);
                btnDeleteNV.setEnabled(enabled);
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // ĐÃ KHAI BÁO LẠI Ở PHÍA TRÊN
    private javax.swing.JButton btnAddNV;
    private javax.swing.JButton btnDeleteNV;
    private javax.swing.JButton btnLoadNV;
    private javax.swing.JButton btnUpdateNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelForm; // Panel bên trái
    private javax.swing.JPanel panelButtons; // Panel chứa các nút
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1; // Thanh chia
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaCN_NV;
    private javax.swing.JTextField txtMaNV;
    // End of variables declaration//GEN-END:variables
}